# Site settings
title: "iBurn 2014 - Burning Man iOS and Android Apps for Offline Maps, Camps, Art and Events"
email: chrisballinger+iburn@gmail.com
description: "iOS and Android apps for offline Burning Man Map, Camps, Art and Events"
baseurl: ""
url: "http://iburnapp.com"
twitter_username: iBurnApp
facebook_page: iBurnApp
github_username:  burning-man-earth

# Build settings
markdown: kramdown
permalink: pretty
